---
- name: Windows functionality check with 2019
  hosts: windows
  become: false
  gather_facts: true
  tasks:
    - name: test connection
      win_ping:
    - name: copy file to remote host
      win_copy:
        src: getitems.ps1
        dest: c:\users\ansible\get-items.ps1

    - name: executing powershell script
      win_shell: c:\users\ansible\get-items.ps1
      args:
        chdir: c:\users\ansible
      register: homedir
    - name: debugging script result
      debug: var=homedir